### ISSUE TITLE
improving usability of the fullscreen-mode (suggestions are welcome)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [punesemu/puNES#345]
Hi Fabio.
I've got some free time and another retro-laptop hehehe, so i tested the emulator for the past few days

I have a few suggestions which can improve the usability of the fullscreen-mode "out-of-the-box":
- Change "Toggle the Menu Bar in fullscreen" shortcut from default "Alt+M" to something like "Esc"
- Duplicate this (show/hide fullscreen menubar) on the RightMouseButton click [nestopia-like behavior].
- Or maybe, instead of RMB, show the menu only when the mouse cursor is at the top of the screen? 
[mesen-like behavior, work only at non-exclusive fullscreen on current build]
This way user can operate settings/rom loading/etc much more faster/more comfortable, i guess.

Maybe You (or bugtesters-guys here) have some more interesting ideas / suggestions than mine?

**Comment by punesemu** [comment]
HI Eugene, another retro-laptop??? :smile: 

> Or maybe, instead of RMB, show the menu only when the mouse cursor is at the top of the screen?
[mesen-like behavior, work only at non-exclusive fullscreen on current build]
This way user can operate settings/rom loading/etc much more faster/more comfortable, i guess.

I really like this idea. Do you have a chance to test this patch? Or do you prefer a compiled version for windows?
[punes_open_menubar_with_mouse.patch ](https://gist.github.com/punesemu/4ec7e08cfaa638ffd365a7c2182aaaeb)

**Comment by punesemu** [comment]
>Change "Toggle the Menu Bar in fullscreen" shortcut from default "Alt+M" to something like "Esc"

I like this too.

**Comment by eugene-s-nesdev** [comment]
Yep, i have an acer-1830t now for a very low-price, and it good enough for "shit-testing" (performance drops/old OSes/еtс).
It can run even winXP if needed, but i installed win7 and will install linux also. Right now, it doesn't have MSVC/MinGW but i will do it soon.
If you can do d3d9-x64 build i can test it right now

**Comment by eugene-s-nesdev** [comment]
Also i've found a small bug, and can replicate it on win7 and win10, both intel and nvidia.
- set FPS-meter OSD (or lag counter something like this) visible
- run game, set fullscreen
- being fullscreen, load another game via menubar
- you'll see the picture and the OSD move-off under the bottom of the screen. This is certainly bug.
- press your shortcut to enter windowed mode, then go fullscreen again - bug is gone.

Can you reproduce it?

**Comment by punesemu** [comment]
[punes D3D9 32bit](https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1).

As for the bug, I can reproduce it (except for the slightly distorted image), I noticed that it only happens under windows. I'll try to understand why.

**Comment by punesemu** [comment]
Ok, I've updated the [punes D3D9 32bit](https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1), I think I've fixed the bug.

**Comment by punesemu** [comment]
> Change "Toggle the Menu Bar in fullscreen" shortcut from default "Alt+M" to something like "Esc"

Updated again [punes D3D9 32bit](https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1).

**Comment by eugene-s-nesdev** [comment]
Thank you. It works like a charm (i5-2500s/intelHD/win10). Much more useful now. I will test it on all my machines too

**Comment by eugene-s-nesdev** [comment]
How to know maximum puNES FPS unthrottled? 
(it' useful thing for testing performance between machines, or speed regressions between builds)

I see strange FPS-meter behavior (maybe bug, maybe not):
- set FPS-meter ON
- set NTSC
- press toggle fast forward (or hold it manually)
- FPS-meter still shows 60 FPS and no more.
- set PAL or Dendy
- press toggle fast forward (or hold it manually)
- FPS-meter shows 32 FPS. Also strange.

**Comment by eugene-s-nesdev** [comment]
Re-tested lastest commit on Nvidia modern machine. All works good too. Thank you!

**Comment by punesemu** [comment]
>I see strange FPS-meter behavior (maybe bug, maybe not):
It's not a bug, the fps you see indicates the graphic frames (which are not the emulator frames), which I also need in the debug environment but it is right to show the PPU frames.

**Comment by punesemu** [comment]
Try with d27fefc.

**Comment by eugene-s-nesdev** [comment]
Works very well and stable, it's much clearer now. 
Thank you. That was an interesting test.

**Comment by punesemu** [comment]
We were both younger :boy:
