### ISSUE TITLE
Disk System loading issues

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#353]
Hi. Mesen 2.0.0 switches and loads the first levels of these ROMs correctly, but they get stuck on puNES:

- [x] `Michael English Daibouken (Japan)` - This gave me an `Err 07` on puNES even with the autoswitch option turned off
- [x] `Moonball Magic (Japan) (Disk Writer)`
- [x] `Super Lode Runner (Japan)` 
- [x] `Ultraman Club - Chikyuu Dakkan Sakusen (Japan) (Rev 1)`

Additionally:

- [x] `Zelda no Densetsu - The Hyrule Fantasy (Japan) (Rev 1)` - `Err 40` before loading the first level
- [x] The `.fds` version of `[...] Game & Watch - Super Mario Bros.` works on puNES, but the `.qd` ROM shows this message: "Please set disk card."
- [x] Autoswitch needs to be disabled for all ROMs with `Kouhen` in their titles, since they are the second disks in their releases and currently give a bootloop. Ideally, puNES would detect them and prompt the user to select their respective `Zenpen`  disks (https://github.com/SourMesen/Mesen/issues/537). Check  `[...] Shinban Tsumeshougi - Tsugi no Itte` too

puNES D3D9 8a6ed11
Windows 10

**Comment by punesemu** [comment]
>The `.fds` version of `[...] Game & Watch - Super Mario Bros.` works on puNES, but the `.qd` ROM shows this message: "Please set disk card."

The `.qd` version is "wrong", every side in QD format must have a size of 65536 bytes while, as can be seen from the size of the file, in this case it has a size of 57344 bytes. In the emulator I do a check to verify that the size is correct otherwise I ignore the side. In my private build I changed this control and now the image is loaded correctly.

**Comment by punesemu** [comment]
Try the last WIP (20b26f482462f376fc3c292048fd9ccfea9ea959).
>`Zelda no Densetsu - The Hyrule Fantasy (Japan) (Rev 1)` - `Err 40` before loading the first level

I don't consider this a problem, the game routine simply tried to read the disc a moment after the auto insert routine had simulated an ejection of the disc. It can happen.

**Comment by anewuser** [comment]
I'm going to report the issue with the Game & Watch Mario ROM to No-Intro.

- [ ] Please check `Michael English Daibouken (Japan).qd`  again. It crashed with`Err 01` on my first try.
- [ ] `Super Lode Runner (Japan).qd` scrolls the screen for you to see the whole level before playing it. puNES seems to be fast-forwarding this.

**Comment by punesemu** [comment]
Please Try the last WIP (fe10203). With this patch I made the recognition of loading/saving on disk more precise, making fast forward more precise. Given the significant changes I tried all the FDS again but if you could do a second check it would be much appreciated. The auto insert algorithm is not an exact science (unfortunately not all games use the same logic for waiting for disc change, I tried to consider all the various possibilities but I think it is impossible that everything goes well for all games) so `Err 01` or `Err 40` may occur which are normally automatically corrected, except in the case of `Michael English Daibouken (Japan)` which waits for a key to be pressed to try again (and perhaps there may be others that work the same way) .

**Comment by anewuser** [comment]
* [ ] Trying to use `[BIOS] Family Computer Disk System (World) (Rev 1) (Game & Watch - Super Mario Bros.).bin` (renamed as `disksys.rom`) to load random games gives a bootloop. Maybe you can show a "Incompatible BIOS detected" message when it doesn't match any of the supported files?
* [ ] Please check `Koneko Monogatari - The Adventures of Chatran (Japan).qd`. It requires a button press to read `Side B` and autoswitch is messing with it
* [ ] `Monitor Puzzle Kineko, The - Kinetic Connection (Japan).qd` and `Monitor Puzzle Kineko, The - Kinetic Connection II (Japan) (Disk Writer).qd` request you to reset the game when `Err 40` occurs. Can anything be done about it?

![Monitor Puzzle Kineko, The - Kinetic Connection II (Japan) (Disk Writer)_000001](https://github.com/punesemu/puNES/assets/6733770/ae46f069-a800-4c89-8b8b-e45f468a53ca)

**Comment by anewuser** [comment]
It happens if autoswitch is enabled and you press the `Start` button too fast on this screen:

![Monitor Puzzle Kineko, The - Kinetic Connection (Japan)_000001](https://github.com/punesemu/puNES/assets/6733770/cf9de29b-ef33-4a23-af54-f87479c95b47)

Load these states and keep hitting `Start`:

[save.zip](https://github.com/punesemu/puNES/files/13640814/save.zip)

**Comment by punesemu** [comment]
I didn't disappear, I rewrote FDS support again. I will contact you when I have everything completed.

**Comment by punesemu** [comment]
Hi André, when you have time can you try the latest WIP (d913e3b)?

**Comment by punesemu** [comment]
>- [ ] Autoswitch needs to be disabled for all ROMs with `Kouhen` in their titles, since they are the second disks in their releases and currently give a bootloop. Ideally, puNES would detect them and prompt the user to select their respective `Zenpen`  disks (https://github.com/SourMesen/Mesen/issues/537). Check  `[...] Shinban Tsumeshougi - Tsugi no Itte` too

For now I have added the possibility of being able to load the image of another Floppy on the fly ([1bae89a](https://github.com/punesemu/puNES/commit/1bae89a2871e3b3b209ee396cb5060eb81b4b751)).

**Comment by anewuser** [comment]
Hello. 

- [ ] Please check all unlicensed ROMs with `Disk 1` and `Disk 2` in their names. Many of them are giving `Illegal Opcode`  errors or getting stuck in autoswitch loops
- [ ] `Famicom Tantei Club - Kieta Koukeisha - Kouhen (Japan).fds` -  `Illegal Opcode` 
- [ ] `Famicom Tantei Club Part II - Ushiro ni Tatsu Shoujo - Kouhen (Japan) (DV 3, 4).fds` -  `Illegal Opcode` 
- [ ] `Puzzle Boys (Japan) (Disk Writer).fds` sometimes crashes with `Error 01` before loading the first level (hold `Fast forward` down and keep pressing `Start`)
- [ ] `Souseiki Fammy - ROM-QD for 256K+64K (Japan) (Unl).fds` gets stuck on the `Now loading` screen. Maybe it should display an `Unsupported device` message?

**Comment by punesemu** [comment]
>- [ ] Please check all unlicensed ROMs with `Disk 1` or `Disk 2` in their names. Many of them are giving `Illegal Opcode`  errors or getting stuck in autoswitch loops
>- [ ] `Famicom Tantei Club - Kieta Koukeisha - Kouhen (Japan).fds` -  `Illegal Opcode` 
>- [ ] `Famicom Tantei Club Part II - Ushiro ni Tatsu Shoujo - Kouhen (Japan) (DV 3, 4).fds` -  `Illegal Opcode` 

Try disabling "Use fast forward when loading the disk/side" and you will see that you will get the classic "Err. 20". To speed up the loading of the bios in this new version I skip the entire license check part:
in `src/core/mappers/mapper_FDS.c` 
```c
		case 0xEF44:
			// Wait after disk insertion
			if (cfg->fds_fast_forward) {
				nes[nidx].c.cpu.PC.w += 2;
				address = nes[nidx].c.cpu.PC.w - 1;
			}
			break;
		case 0xEFAF:
			// Wait license
			if (cfg->fds_fast_forward) {
				nes[nidx].c.cpu.AR = 0;
				nes[nidx].c.cpu.PC.w += 2;
				address = nes[nidx].c.cpu.PC.w - 1;
			}
			break;
		case 0xF46E:
			// License check
			if (cfg->fds_fast_forward) {
				nes[nidx].c.cpu.PC.w += 2;
				address = nes[nidx].c.cpu.PC.w - 1;
			}
			break;
```
This change generates the illegal opcode but is not an error.

>- [ ] `Puzzle Boys (Japan) (Disk Writer).fds` sometimes crashes with `Error 01` before loading the first level (hold `Fast forward` down and keep pressing `Start`)

Yes you are right, I think I will have to disable autoinsert for this image

>- [ ] `Souseiki Fammy - ROM-QD for 256K+64K (Japan) (Unl).fds` gets stuck on the `Now loading` screen. Maybe it should display an `Unsupported device` message?

I will keep you informed.

**Comment by punesemu** [comment]
>- [ ] Please check all unlicensed ROMs with `Disk 1` or `Disk 2` in their names. Many of them are giving `Illegal Opcode`  errors or getting stuck in autoswitch loops
>- [ ] `Famicom Tantei Club - Kieta Koukeisha - Kouhen (Japan).fds` -  `Illegal Opcode` 
>- [ ] `Famicom Tantei Club Part II - Ushiro ni Tatsu Shoujo - Kouhen (Japan) (DV 3, 4).fds` -  `Illegal Opcode` 

Fixed with 6358116.

**Comment by punesemu** [comment]
>- [x] `Puzzle Boys (Japan) (Disk Writer).fds` sometimes crashes with `Error 01` before loading the first level (hold `Fast forward` down and keep pressing `Start`)

The game routine tried to read the disc a moment after the auto insert routine had simulated an ejection of the disc.  Unlike `Zelda no Densetsu - The Hyrule Fantasy (Japan) (Rev 1)` it doesn't try to read again but remains at the Err 01 screen, so it's not compatible with the auto insert (9e53074).

**Comment by punesemu** [comment]
>- [x] `Souseiki Fammy - ROM-QD for 256K+64K (Japan) (Unl).fds` gets stuck on the `Now loading` screen. Maybe it should display an `Unsupported device` message?

Yes, you are right again, this FDS requires specific unsupported hardware (2ce45cf).

**Comment by anewuser** [comment]
The first two games with `Disk 1` I tested are still getting into an autoswitch loop when they ask for a disk change before loading their first levels.

Wouldn't it be better to add `Disk 1` and `Disk 2` to this statement? 

https://github.com/punesemu/puNES/blob/9e530749ae4a7cc914d4b4cfceabd084c5c449c1/src/core/fds.c#L1051C2-L1051C2

**Comment by punesemu** [comment]
Yes, I can (8e4c491).

**Comment by anewuser** [comment]
Hi. Please check if you get a green screen while loading the first level of `SD Gundam World - Gachapon Senshi - Scramble Wars (Japan) (Rev 1) (Wii Virtual Console).qd` .

Also, the main character apparently won't move in these revisions  of Nazo no Murasamejou:

- [ ] `Nazo no Murasamejou (Japan) (Wii and Wii U Virtual Console).qd`
- [ ] `Nazo no Murasamejou (World) (Ja) (3DS Virtual Console).qd`

**Comment by punesemu** [comment]
> - [ ] Also, the main character apparently won't move on these revisions of Nazo no Murasamejou:  `Nazo no Murasamejou (Japan) (Wii and Wii U Virtual Console).qd` and `Nazo no Murasamejou (World) (Ja) (3DS Virtual Console).qd`

I checked and honestly I don't think it's an emulator problem. Have you tried with any other emulator?

**Comment by punesemu** [comment]
- [ ] Please check if you get a green screen while loading the first level of `SD Gundam World - Gachapon Senshi - Scramble Wars (Japan) (Rev 1) (Wii Virtual Console).qd` 

Yes and even in this case I don't think it depends on the emulator. I think these `Wii and Wii U Virtual Console` and `3DS Virtual Console` versions are modified to work with the proprietary emulator.

**Comment by anewuser** [comment]
Alright. I couldn't get them to work on other emulators either, but asked you anyway to be sure.  

These days I went through the whole QD set and haven't found any other problem, so I think this issue can be closed now.

**Comment by anewuser** [comment]
@punesemu If puNES is closed and I try to launch it from the command line with a disk image, the latest build opens and then closes itself. This doesn't happen if puNES is already running. Please check if you can reproduce this on Windows.

**Comment by punesemu** [comment]
Yes, I confirm that this problem only exists with the Windows version, I will investigate and let you know.

**Comment by punesemu** [comment]
Fixed with 218114d.

**Comment by anewuser** [comment]
Thank you! Please check the title screen of `Vs. Excitebike (Japan) (En).qd` too. It keeps fast-forwarding:

<details>
<summary>Video</summary>

https://github.com/punesemu/puNES/assets/6733770/30283edf-3ce1-4cc2-8e18-d314c2f9ec3c

</details>

**Comment by punesemu** [comment]
I haven't disappeared, in this period between the rewrite of the NSF player and life I have little time, but as soon as I have a little more free time I will take a look at all the reports you have given me.

**Comment by punesemu** [comment]
Fixed with [0291a4e](https://github.com/punesemu/puNES/commit/0291a4ee9347ffdeb8ed6b9fdaa3276d317d44e4).
